declare module "emoji-datasource-google" {
  // types generated by quicktype

  export interface SkinVariation {
    unified: string;
    non_qualified: null | string;
    image: string;
    sheet_x: number;
    sheet_y: number;
    added_in: string;
    has_img_apple: boolean;
    has_img_google: boolean;
    has_img_twitter: boolean;
    has_img_facebook: boolean;
    obsoletes?: string;
    obsoleted_by?: string;
  }

  export type Category =
    | "Activities"
    | "Animals & Nature"
    | "Component"
    | "Flags"
    | "Food & Drink"
    | "Objects"
    | "People & Body"
    | "Smileys & Emotion"
    | "Symbols"
    | "Travel & Places";

  export interface Emoji {
    name: string;
    unified: string;
    non_qualified: null | string;
    docomo: null | string;
    au: null | string;
    softbank: null | string;
    google: null | string;
    image: string;
    sheet_x: number;
    sheet_y: number;
    short_name: string;
    short_names: string[];
    text: null | string;
    texts: string[] | null;
    category: Category;
    subcategory: string;
    sort_order: number;
    added_in: string;
    has_img_apple: boolean;
    has_img_google: boolean;
    has_img_twitter: boolean;
    has_img_facebook: boolean;
    skin_variations?: Record<string, SkinVariation>;
    obsoletes?: string;
    obsoleted_by?: string;
  }

  declare const emojiList: Emoji[];
  export default emojiList;
}
