name: Node CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 22
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm run build --if-present
        npm test
        npm run test:browser
